import DGNG.Theorem1
import DGNG.Theorem2
import DGNG.Theorem3
import DGNG.Theorem3_n
import DGNG.Theorem1_n
import DGNG.Theorem1_K3
import DGNG.LaSalle
import DGNG.LaSalle_n
import DGNG.EnergyBound_n
